version: '3.1'

services:
    rabbitmq:
        image: "rabbitmq:3-management"
        hostname: 'rabbit'
        ports:
          - "15672:15672"
          - "5672:5672"
        labels: 
            NAME: "rabbitmq"
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
            - ./rabbit-isolated.conf:/etc/rabbitmg.config
    
volumes:
    rabbitmq-data:

    
